#!/usr/bin/env python3
"""Pin swCrossRatio: which Mobius map u -> m has lambda(tau_curve(u)) = m(u)?

Per audit/GENUS1_PERIODS_PLAN.md (C-route, next milestone after C1h): before the Lean
definition of swCrossRatio is written, determine it by computation that does NOT assume
the answer:

  1. compute the A/B periods of dx/y on the SW curve y^2 = (x^2-u)^2 - L^4 by DIRECT
     contour quadrature between branch points, with the sqrt branch tracked continuously
     along the path (no reduction to K/E formulas, which would presuppose the reduction
     being pinned);
  2. tau_curve(u) := (B period)/(A period), normalized into the upper half plane;
  3. mhat(u) := lambda(tau_curve(u)) via the theta series (repo conventions,
     q = exp(pi*i*tau), lambda = theta2^4/theta3^4);
  4. compare mhat(u) against the candidate Mobius maps sending the three singular
     points {u = L^2, u = -L^2, u = infinity} to {0, 1, infinity} in some order -- the
     six anharmonic candidates generated by m0 = 2 L^2/(u + L^2).

The winner (checked at several u, two Lambda values, real and complex u) is the pin.
Also cross-checked against the C1 bridge: tau_curve(u) vs i*K(1-m)/K(m) at m = m0(u).

Method note: each segment integral between two roots p,q of the monic quartic
f(x) = (x^2-u)^2 - L^4 uses x = p + (q-p) sin^2(phi), under which
dx/y = 2 (q-p) dphi / sqrt(W(phi)) with W = -(q-p)^2 (x - r3)(x - r4) EXACTLY
(r3, r4 the other two roots) -- no endpoint singularity, no cancellation; sqrt(W) is
branch-tracked along the phi-grid. Simpson integration.
"""
import mpmath as mp

mp.mp.dps = 30
N_THETA = 60

def theta3(tau):
    return mp.fsum(mp.e ** (mp.pi * 1j * tau * (n * n)) for n in range(-N_THETA, N_THETA + 1))

def theta2(tau):
    return mp.fsum(mp.e ** (mp.pi * 1j * tau * (n + mp.mpf(1) / 2) ** 2)
                   for n in range(-N_THETA, N_THETA + 1))

def lam(tau):
    return theta2(tau) ** 4 / theta3(tau) ** 4

def seg_period(p, q, r3, r4, n=4000):
    """integral_p^q dx / sqrt((x-p)(x-q)(x-r3)(x-r4)), branch tracked, Simpson."""
    h = (mp.pi / 2) / n
    vals = []
    w_prev = None
    for k in range(n + 1):
        phi = k * h
        t = mp.sin(phi) ** 2
        x = p + (q - p) * t
        W = -((q - p) ** 2) * (x - r3) * (x - r4)
        s = mp.sqrt(W)
        if w_prev is not None and abs(-s - w_prev) < abs(s - w_prev):
            s = -s
        w_prev = s
        vals.append(2 * (q - p) / s)
    total = vals[0] + vals[-1]
    total += 4 * mp.fsum(vals[k] for k in range(1, n, 2))
    total += 2 * mp.fsum(vals[k] for k in range(2, n, 2))
    return total * h / 3

def tau_curve(u, L):
    e1 = mp.sqrt(u + L ** 2)   # outer branch points +-e1
    e2 = mp.sqrt(u - L ** 2)   # inner branch points +-e2
    # A-cycle encircles the cut [e2, e1]: both sheets, so 2 * segment; the B-cycle
    # threads the middle region once per sheet-crossing: 1 * segment. (The first run
    # of this script had tau off by exactly 2 -- caught by the tau(3) = i sanity
    # anchor and by tau/2 matching a candidate to 5e-32; normalization pinned.)
    pA = 2 * seg_period(e2, e1, -e1, -e2)
    pB = seg_period(-e2, e2, e1, -e1)
    tau = pB / pA
    if mp.im(tau) < 0:
        tau = -tau
    return tau

def candidates(u, L):
    m0 = 2 * L ** 2 / (u + L ** 2)
    return {
        "2L^2/(u+L^2)          ": m0,
        "1 - 2L^2/(u+L^2)      ": 1 - m0,
        "(u+L^2)/(2L^2)        ": 1 / m0,
        "1/(1 - 2L^2/(u+L^2))  ": 1 / (1 - m0),
        "m0/(m0-1)             ": m0 / (m0 - 1),
        "(m0-1)/m0             ": (m0 - 1) / m0,
    }

results = []
def check(name, cond, detail=""):
    results.append((name, bool(cond), detail))
    print(f"  [{'PASS' if cond else 'FAIL'}] {name}{('  ' + detail) if detail else ''}")

TOL = mp.mpf(10) ** (-12)   # quadrature-limited (Simpson n=4000); pin needs O(1) discrimination

print("=== sanity: u = 3, L = 1 is the self-dual point (m = 1/2, tau = i) ===")
t = tau_curve(mp.mpc(3), mp.mpf(1))
check("tau(3) = i", abs(t - 1j) < mp.mpf(10) ** (-10), f"tau={mp.nstr(t, 12)}")

print("=== the pin: mhat(u) = lambda(tau_curve(u)) vs the six anharmonic candidates ===")
SAMPLES = [(mp.mpc(5), mp.mpf(1)), (mp.mpc(10), mp.mpf(1)), (mp.mpc('2.2'), mp.mpf(1)),
           (mp.mpc(7), mp.mpf('1.7')),                     # second Lambda: scale covariance
           (mp.mpc(3, 2), mp.mpf(1)), (mp.mpc(-1, 4), mp.mpf(1)),   # complex u
           (mp.mpc('0.5', '2.5'), mp.mpf(1))]
tally = {k: 0 for k in candidates(mp.mpc(5), mp.mpf(1))}
for u, L in SAMPLES:
    mhat = lam(tau_curve(u, L))
    best, bestres = None, mp.inf
    for name, val in candidates(u, L).items():
        r = abs(mhat - val)
        if r < bestres:
            best, bestres = name, r
    tally[best] += 1
    check(f"u={mp.nstr(u,4)} L={mp.nstr(L,3)} -> {best.strip()}", bestres < TOL,
          f"res={mp.nstr(bestres, 3)}")
winner = max(tally, key=tally.get)
check(f"UNIQUE winner across all samples: {winner.strip()}", tally[winner] == len(SAMPLES),
      f"tally={ {k.strip(): v for k, v in tally.items() if v} }")

print("=== cross-check vs the C1 bridge: tau_curve(u) matches i K(1-m)/K(m) at m = m0(u) ===")
for u, L in SAMPLES[:5]:
    m0 = 2 * L ** 2 / (u + L ** 2)
    t_curve = tau_curve(u, L)
    t_K = 1j * mp.ellipk(1 - m0) / mp.ellipk(m0)
    # agreement up to Gamma(2) is what lambda-matching certifies; here check literal equality
    # of the principal representatives (they should coincide for these u away from the cut)
    check(f"tau bridge  u={mp.nstr(u,4)}", abs(t_curve - t_K) < TOL,
          f"res={mp.nstr(abs(t_curve - t_K), 3)}")

print("=== normalization uniqueness: 2*tau and tau/2 do NOT match any candidate ===")
u, L = mp.mpc(5), mp.mpf(1)
for scale, nm in ((2, "2*tau"), (mp.mpf(1) / 2, "tau/2")):
    mh = lam(scale * tau_curve(u, L))
    r = min(abs(mh - v) for v in candidates(u, L).values())
    check(f"{nm} matches nothing", r > mp.mpf('1e-3'), f"closest={mp.nstr(r, 3)}")

ok = all(r[1] for r in results)
npass = sum(1 for r in results if r[1])
print(f"\n=== {'ALL PASS' if ok else 'FAILURES PRESENT'} : "
      f"{npass}/{len(results)} checks, dps={mp.mp.dps} ===")
raise SystemExit(0 if ok else 1)
